"""Safe Markdown rendering helpers for the Flask presentation layer."""

from __future__ import annotations

import re

import markdown
from markupsafe import escape


_OPENING_TAG_RE = re.compile(r"<(?P<tag>table|thead|tbody|tr|th|td)(?P<attrs>[^>]*)>", re.IGNORECASE)
_GOVUK_CLASSES = {
    "table": "govuk-table",
    "thead": "govuk-table__head",
    "tbody": "govuk-table__body",
    "tr": "govuk-table__row",
    "th": "govuk-table__header",
    "td": "govuk-table__cell",
}


def _decorate_table_tag(match: re.Match[str]) -> str:
    """Add the appropriate GOV.UK class to a generated table element."""
    tag = match.group("tag").lower()
    attrs = match.group("attrs")
    css_class = _GOVUK_CLASSES[tag]
    class_match = re.search(r'\bclass=(?P<quote>["\'])(?P<value>.*?)(?P=quote)', attrs, re.IGNORECASE)

    if class_match:
        classes = class_match.group("value").split()
        if css_class not in classes:
            classes.append(css_class)
        replacement = f'class={class_match.group("quote")}{" ".join(classes)}{class_match.group("quote")}'
        attrs = attrs[: class_match.start()] + replacement + attrs[class_match.end() :]
    else:
        attrs = f' class="{css_class}"{attrs}'

    if tag == "th" and not re.search(r"\bscope\s*=", attrs, re.IGNORECASE):
        attrs += ' scope="col"'
    return f"<{tag}{attrs}>"


def render_markdown_content(content_str: str) -> str:
    """Convert Markdown into safe HTML with GOV.UK table classes.

    User/model-provided raw HTML is escaped before Markdown processing. This keeps
    Jinja's later ``safe`` rendering limited to HTML generated by this function.
    """
    if not content_str:
        return ""

    html = markdown.markdown(
        str(escape(str(content_str))),
        extensions=["tables", "fenced_code", "nl2br"],
        output_format="html5",
    )
    html = _OPENING_TAG_RE.sub(_decorate_table_tag, html)
    html = html.replace(
        '<table class="govuk-table">',
        '<div class="govuk-table-scroll-container"><table class="govuk-table">',
    )
    html = html.replace("</table>", "</table></div>")
    return html
